name: Docker

on:
  push:
    tags: ["*"]
    branches:
      - "main"
  pull_request:
    branches: ["**"]

jobs:
  build:
    permissions:
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: davidkarlsson416/scout:123
      - name: Evaluate policy
        uses: docker/scout-action@v1
        continue-on-error: true
        with:
          command: compare
          exit-code: true
          environment: staging
          organization: davidkarlsson416
          image: davidkarlsson416/scout:123
